# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04ac9b8ea46e326598ee2386526bd27b4d7a4c8854f0bdae8b70e3c9cecc04329987170cc2894005ed0402bf6235004709edeb8569362a46c1821c95d3e3e9fc

test:
  secret_key_base: dd4f7ad0cdd5ee3f1371b93a2400ffe675bb8d7a2e3cb1f5747314fb8e31950fb4b9b489d8af55aa2569d563e487a60ec4c3ee913ef35eaf8334d767891e428b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
